name: auto_update_readme

run-name: Write ${{ github.actor }}'s coding-test study README file 🚀

on: [push]

permissions:
  contents: write
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-leetcode
      - name: Run update.py
        run: |
          python update.py
      - name: Commit changes
        run: |
          git config --global user.name "Cho-Hyun-Seung"
          git config --global user.email "toki0327@naver.com"
          git add -A
          git commit -am "auto update readme"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
